/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        tertiary: "#852b00", 
        "surface-tint": "#1353d8", 
        "surface-container-highest": "#e1e3e4", 
        "inverse-surface": "#2e3132", 
        secondary: "#555f6d", 
        "on-primary-container": "#d4dcff", 
        "on-tertiary-fixed": "#380d00", 
        "surface-container": "#edeeef", 
        surface: "#f8f9fa", 
        "tertiary-container": "#ad3b00", 
        "on-tertiary-container": "#ffd4c5", 
        primary: "#003fb1", 
        "primary-fixed": "#dbe1ff", 
        "surface-container-lowest": "#ffffff", 
        "on-surface": "#191c1d", 
        "secondary-container": "#d6e0f1", 
        "on-primary-fixed": "#00174d", 
        "on-secondary-fixed": "#121c28", 
        "on-primary": "#ffffff", 
        "surface-container-low": "#f3f4f5", 
        "surface-variant": "#e1e3e4", 
        "inverse-primary": "#b5c4ff", 
        "on-background": "#191c1d", 
        background: "#f8f9fa", 
        "on-surface-variant": "#434654", 
        "secondary-fixed-dim": "#bdc7d8", 
        "secondary-fixed": "#d9e3f4", 
        "inverse-on-surface": "#f0f1f2", 
        "tertiary-fixed-dim": "#ffb59a", 
        "primary-fixed-dim": "#b5c4ff", 
        "on-error-container": "#93000a", 
        "outline-variant": "#c3c5d7", 
        "surface-container-high": "#e7e8e9", 
        "on-secondary": "#ffffff", 
        "tertiary-fixed": "#ffdbcf", 
        "on-primary-fixed-variant": "#003dab", 
        "surface-bright": "#f8f9fa", 
        error: "#ba1a1a", 
        "surface-dim": "#d9dadb", 
        "on-error": "#ffffff", 
        "error-container": "#ffdad6", 
        outline: "#737686", 
        "on-tertiary-fixed-variant": "#802a00", 
        "primary-container": "#1a56db", 
        "on-tertiary": "#ffffff", 
        "on-secondary-container": "#596372", 
        "on-secondary-fixed-variant": "#3e4755"
      }, 
      fontFamily: {
        headline: ["Manrope", "sans-serif"], 
        body: ["Inter", "sans-serif"], 
        label: ["Inter", "sans-serif"], 
        display: ["Manrope", "sans-serif"]
      }, 
      borderRadius: {
        DEFAULT: "0.5rem", 
        lg: "1rem", 
        xl: "1.5rem", 
        full: "9999px"
      }
    },
  },
  plugins: [],
}
